#
# Thank you for downloading CrownAreaReset!
# If you have any questions, suggestions or need help, please do not hesitate and
# join our discord: https://dsc.gg/crowndevelopment to ask for help!
# We are there to assist you.
#

# enable the regen broadcast messages
area-regen-broadcast: true

player-pushback:
  enabled: true # disable this if you dont want the players to be pushed up when the area is regenerating
  effects: # set the effects players get when boosted up
    - BLINDNESS
    - SLOW_FALLING
    - SLOW