name: CrownAreaReset
version: 1.1.2
author: Obey
website: https://builtbybit.com/resources/areareset.61809/

main: de.obey.crown.noobf.CrownAreaReset
api-version: '1.20'
folia-supported: true

softdepend:
  - PlaceholderAPI

depends:
  - CrownCore
  - FastAsyncWorldEdit
  - WorldGuard

commands:
  crownareareset:
    aliases: [car]