name: CrownAreaReset
version: 1.0.2
author: Obey
website: https://builtbybit.com/resources/areareset.61809/

main: de.obey.crown.noobf.CrownAreaReset
api-version: '1.20'
commands:
  crownareareset:
    aliases: [car]


