name: CrownAreaReset
version: 1.0.7
author: Obey
website: https://builtbybit.com/resources/areareset.61809/

main: de.obey.crown.noobf.CrownAreaReset
api-version: '1.20'
folia-supported: true

depends:
  - CrownCore

commands:
  crownareareset:
    aliases: [car]